public enum EStzNativeAction
{
	UNKNOWN,
    INITIALIZE,
    ON_CHANGED_NETWORK_STATUS,
    LOCAL_NOTIFICATION_ADD,
    LOCAL_NOTIFICATION_CANCEL,
    LOCAL_NOTIFICATION_ALL_CANCEL,
    APNS_NOTIFICATION_REGIST,
	SHOW_ALERT,
    GET_PUSH_ID,
    SET_TEXT_TO_SYSTEM_CLIPBOARD,
	REQUEST_PERMISSIONS,
    START_DEVICE_LOADING,	
    STOP_DEVICE_LOADING,
    INIT_APPLE_ACCOUNT,
    LOGIN_APPLE_ACCOUNT,
    LOGOUT_APPLE_ACCOUNT,
    SET_KEYCHAIN_VALUE,
    GET_KEYCHAIN_VALUE,
    SET_SHARED_VALUE,
    GET_SHARED_VALUE,
    UUID_WITH_KEYCHAIN,
	ENABLE_SECURE_DISPLAY,
    CLEAR_INSTALL_REFERRER,
    GET_LANGUAGE,
    GET_FREE_SPACE_MB,
    GET_SCHEME_DATA,
    CLEAR_SCHEME_DATA,
    GET_NETWORK_STATUS,
    GET_STIMER,
    IS_INSTALLED,
    GET_PERMISSION_GRANT_TYPE,
    GET_ALL_UNGRANTED_PERMISSIONS,
    OPEN_APP_DETAIL,
    IN_APP_UPDATE_DOWNLOAD,
    IN_APP_UPDATE_INSTALL_IMMEDIATE,
    IN_APP_UPDATE_INSTALL_FLEXIBLE,
    RISE_CRASH,
    SET_RESERVED_WORD,
    GET_AND_CLEAR_DEEPLINK,
    
    //2.1.0
	GET_ATT_STATUS,
	REQUEST_ATT,

	//2.1.1
	GET_IDFA,
	
	//2.1.3
	SET_UUID,

	//2.1.4
	SEND_EMAIL
}